# 使用 Node.js 官方镜像作为基础镜像
FROM node:20


# 设置镜像源为阿里云镜像源
RUN npm config set registry https://registry.npmmirror.com

# 安装 pnpm
RUN npm install -g pnpm

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN pnpm install

# 复制应用的源代码
COPY . .

RUN npm run build
