version: '3'
services:
  client:
    build:
      context: .
      dockerfile: client/dockerfile

  server:
    build:
      context: .
      dockerfile: server/dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "80:80"