# 使用官方 Node.js 镜像作为基础镜像
FROM node:20 AS builder

WORKDIR /usr/src/app

# 设置镜像源为阿里云镜像源
RUN npm config set registry https://registry.npmmirror.com

# 安装 pnpm
RUN npm install -g pnpm


RUN npm install @nestjs/cli -g

# 复制 package.json 和 package-lock.json
COPY package*.json .

# 安装应用依赖
RUN pnpm install

# 复制应用代码
COPY . .

# 构建应用
RUN npm run build

FROM node:20

WORKDIR /usr/src/app

# 从 builder 阶段复制构建好的 /usr/src/app/dist 和 /usr/src/app/node_modules 的文件到当工作目录
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "dist/main.js"]