# 使用官方 Node.js 镜像作为基础镜像
FROM node:20

# 设置工作目录
WORKDIR /app

# 安装 pnpm
RUN npm install -g pnpm

# 设置镜像源为阿里云镜像源
RUN npm config set registry https://registry.npmmirror.com

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装应用依赖
RUN pnpm install

# 复制应用代码
COPY . .

# 构建应用
CMD npm run
docker logs myapp
